### PR TITLE
Added some typehints

### PR DESCRIPTION
**Pull request by guidofaecke**
Provide a narrative description of what you are trying to accomplish:

- [ ] Are you fixing a bug?
  - [ ] Detail how the bug is invoked currently.
  - [ ] Detail the original, incorrect behavior.
  - [ ] Detail the new, expected behavior.
  - [ ] Base your feature on the `master` branch, and submit against that branch.
  - [ ] Add a regression test that demonstrates the bug, and proves the fix.
  - [ ] Add a `CHANGELOG.md` entry for the fix.

- [ ] Are you creating a new feature?
  - [ ] Why is the new feature needed? What purpose does it serve?
  - [ ] How will users use the new feature?
  - [ ] Base your feature on the `develop` branch, and submit against that branch.
  - [ ] Add only one feature per pull request; split multiple features over multiple pull requests
  - [ ] Add tests for the new feature.
  - [ ] Add documentation for the new feature.
  - [ ] Add a `CHANGELOG.md` entry for the new feature.

- [ ] Is this related to quality assurance?
  

- [ ] Is this related to documentation?

### CODE REVIEW

**Review by guidofaecke — COMMENTED** [review]
Looking good so far!

**Comment by arueckauer** [comment]
@guidofaecke That's it. :) If I do not stumble upon something in my dreams, I won't push any other changes. From my part this is ready-for-review.

**Comment by guidofaecke** [comment]
You have way too much time on your hand :laughing:   
While working on my regular projects, I still need to finish up my test case for some doctrine issues.
That's why I didn't make it too far.
Anyway, awesome job! Couldn't do it better!
...now I'm curious how the complete zend-db would stand up against my personal PHPCS and PHPStan setup :rofl: It probably would fall apart after the first 100 lines...

**Comment by arueckauer** [comment]
After the last commit I felt bad and want to apologize, since I left almost no work over for you. Sorry!

Yes, coding-standard and static analysis show still quite a few issues. I did handle some, but I a waiting for the next release of `zend-coding-standard` which should cover most of if not all cs issues.

Out of curiosity: You merged your branch into the `3.0.0`. How do you plan to PR to the origin repo?
Edit: Never mind, you already created the PR. :)

**Comment by guidofaecke** [comment]
Don't feel bad, I have enough things to work on :smile: 

The PR has a merge conflict, looks like Select.php changed on zendframework/zend-db in between. 
I will check it out shortly.

**Pull request merged**
